.api-common:
  rules:
    - changes:
      - api/*

build-push-api-image:
  extends: .api-common
  stage: build-push
  image:
      name: $DOMAIN_NAME_TCR/software-development-executor/gcr.io/kaniko-project/executor:v1.23.2-debug
      entrypoint: [""]
  before_script:
        - echo "$TCR_CERTIFICATE" >> /kaniko/ssl/certs/ca-certificates.crt
  script:
    - echo "API_IMAGE_NAME $API_IMAGE_NAME"
    - echo "CI_PROJECT_DIR $CI_PROJECT_DIR"
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$DOMAIN_NAME_TCR\":{\"auth\":\"$(printf "%s:%s" "$TCR_ROBOT_ACCOUNT" "$TCR_ROBOT_TOKEN" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
        # Run Kaniko build and push Docker Image
    - /kaniko/executor
      --context "$CI_PROJECT_DIR"
      --dockerfile "$CI_PROJECT_DIR/api/Dockerfile"
      --destination "$API_IMAGE_NAME"

deploy-api-image:
  extends: .api-common
  stage: deploy
  image: $DOMAIN_NAME_TCR/hubdocker/openshift/origin-cli
  before_script:
      - oc login "$OCP_NONPROD_URL" --token="$OCP_TOKEN_DEV" --insecure-skip-tls-verify --loglevel=8
      - oc project $OCP_NAMESPACE_DEV 2> /dev/null
  script:
    - oc set image deployment/nam1-api nam1-api=$API_IMAGE_NAME
    - oc rollout status deployment/nam1-api
